version: "3.8"
services:
  server:
    dockerfile: .
    container_name: javaApp
    ports:
      - "8080:8080"
    networks:
      - Bridge-Zadanie-1
    depends_on:
      - database

  database:
    image: mysql
    container_name: Full2020_086349
    environment:
      MYSQL_DATABASE: shoutbox
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: klitwynenko
      MYSQL_PASSWORD:
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    networks:
      Bridge-Zadanie-1:
        ipv4_address: 10.0.10.3

networks:
  Bridge-Zadanie-1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.0/24